[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Netlify Identity
[context.production.environment]
  NETLIFY_USE_YARN = "false"
