backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "manga"
    label: "Manga"
    folder: "src/data/mangas"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Cover URL", name: "cover", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Status", name: "status", widget: "select", options: ["ongoing", "completed", "hiatus"] }
      - { label: "Genres", name: "genres", widget: "list" }
      - label: "Chapters"
        name: "chapters"
        widget: "list"
        fields:
          - { label: "Chapter Number", name: "chapter", widget: "number" }
          - { label: "Images", name: "images", widget: "list" }
